### PR TITLE
Add Laravel 6.0 support

### PR DESCRIPTION
**Pull request by DariusIII**

### CODE REVIEW

**Comment by wandersonwhcr** [comment]
If we update only `illuminate/support` and not other dependencies and `composer.lock`, we will break development instalation and tests.

**Comment by wandersonwhcr** [comment]
Executing

```bash
composer update illuminate/support
```

to update `composer.lock` just for package, we receive this output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating illuminate/support (v5.5.2 => v5.5.39): Loading from cache
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

It didn't update the package to `6.0`.

**Comment by wandersonwhcr** [comment]
and updating every Laravel package:

```bash
composer update illuminate/{support,container,contracts}
```

we receive

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 3 updates, 0 removals
  - Updating illuminate/contracts (v5.5.2 => v5.6.39): Downloading (100%)         
  - Updating illuminate/support (v5.5.39 => v5.6.11): Downloading (100%)         
  - Updating illuminate/container (v5.5.2 => v5.6.39): Downloading (100%)         
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

and, again, we didn't update to `6.0`

**Comment by wandersonwhcr** [comment]
I found other packages to update:

```bash
composer update illuminate/{support,container,contracts} nesbot/carbon symfony/translation
```

Now we have an update.

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 5 updates, 0 removals
  - Installing symfony/translation-contracts (v1.1.6): Loading from cache
  - Updating symfony/translation (v3.3.9 => v4.3.4): Loading from cache
  - Updating nesbot/carbon (1.22.1 => 2.24.0): Loading from cache
  - Updating illuminate/contracts (v5.6.39 => v6.0.0): Loading from cache
  - Updating illuminate/support (v5.6.11 => v6.0.0): Loading from cache
  - Updating illuminate/container (v5.6.39 => v6.0.0): Loading from cache
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

**Comment by wandersonwhcr** [comment]
... and we broke the tests.

```
composer test
> parallel-lint src
PHP 7.3.9 | 10 parallel jobs
....                                                         4/4 (100 %)


Checked 4 files in 0 seconds
No syntax error found
> phpunit
PHPUnit 6.3.1 by Sebastian Bergmann and contributors.

...F..........                                                    14 / 14 (100%)

Time: 41 ms, Memory: 6.00MB

There was 1 failure:

1) IlluminateTest\Romans\Providers\RomansProviderTest::testDeferred
Failed asserting that false is true.

/home/wanderson/Htdocs/wandersonwhcr/illuminate-romans/test/Providers/RomansProviderTest.php:30

FAILURES!
Tests: 14, Assertions: 35, Failures: 1.
Script phpunit handling the test event returned with error code 1
```

**Comment by wandersonwhcr** [comment]
Checking the new Laravel 6.0 documentation, deferred service providers must implement `Illuminate\Contracts\Support\DeferrableProvider`.

```diff
diff --git a/src/Providers/RomansProvider.php b/src/Providers/RomansProvider.php
index f709f4f..254d312 100644
--- a/src/Providers/RomansProvider.php
+++ b/src/Providers/RomansProvider.php
@@ -2,6 +2,7 @@
 
 namespace Illuminate\Romans\Providers;
 
+use Illuminate\Contracts\Support\DeferrableProvider;
 use Illuminate\Support\ServiceProvider;
 use Romans\Filter\IntToRoman as IntToRomanFilter;
 use Romans\Filter\RomanToInt as RomanToIntFilter;
@@ -12,7 +13,7 @@ use Romans\Parser\Parser;
 /**
  * Romans Provider
  */
-class RomansProvider extends ServiceProvider
+class RomansProvider extends ServiceProvider implements DeferrableProvider
 {
     /**
      * {@inheritdoc}
```

**Comment by wandersonwhcr** [comment]
Now tests are working well on Laravel 6.0.

But we broke Laravel 5.5 because it doesn't have `DeferrableProvider` contract.

**Review by wandersonwhcr — CHANGES_REQUESTED** [review]
Please, read all conversation and update your pull request.

I will increase the major version.

**Comment by DariusIII** [comment]
I'll close this PR and make a proper one with all the needed changes, as this PR was created online.

**Pull request closed without merging**
