### PR TITLE
Laravel 9.x support

### PR DESCRIPTION
**Pull request by sylfel**
Laravel 9.x support and php constraint >= 8.0 like in romans library

### CODE REVIEW

**Comment by wandersonwhcr** [comment]
@sylfel ty

I will update dependencies and try to integrate your PR.

**Comment by wandersonwhcr** [comment]
@sylfel can you check if my changes are the same that you sent before?

Also, you will need to update your dependency to use version `^3.0`.

**Comment by sylfel** [comment]
Hi @wandersonwhcr  !
No my changes are different, and your change don't work with laravel 9

`illuminate-romans` require `illuminate/support ^8.35` or Laravel 9.x provide `illuminate/support 9.x`

All your last change are good, and for perfectly

**Comment by wandersonwhcr** [comment]
@sylfel merged!

ty :partying_face:

**Comment by wandersonwhcr** [comment]
https://github.com/wandersonwhcr/illuminate-romans/releases/tag/v3.0.0

Please, make sure you are using `wandersonwhcr/illuminate-romans: ^3.0` into your `package.json`.

Happy Coding!

**Comment by sylfel** [comment]
ty @wandersonwhcr  ! 
It work perfectly

**Pull request merged**
